name: PHP Composer

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        os: [ ubuntu-latest ]
        include:
          - php: 7.1
            packages: symfony/symfony=3.4.*
          - php: 7.1
            packages: symfony/symfony=4.0.*'

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: json, mbstring
        tools: composer
    - name: Show PHP and composer version
      run: php -v && composer -V

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      # if: steps.composer-cache.outputs.cache-hit != 'true'
      run: |
        echo ${PACKAGES}
        composer require --no-update ${PACKAGES}
        composer install --prefer-source
      env:
        PACKAGES: ${{ matrix.packages}}

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: ./vendor/bin/phpunit
